name: 锻炼

on:
  workflow_dispatch:
  schedule:
    - cron: '*/45 0-12 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    steps:
      - name: Checkout
        run: |
          git clone https://github.com/jiange146/jingdong.git ~/jingdong
      - name: Use Node.js 14.x
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - name: npm install
        run: |
          cd ~/jingdong
          npm install
          npm install cron
          npm install request
      - name: '运行 【锻炼】'
        run: |
          cd ~/jingdong   
          node js/锻炼.js